name: 機能追加・機能拡張
description: 新機能の追加、または既存機能の拡張を提案する
labels:
  - "type:feature"

body:
  - type: markdown # 書き方の説明
    attributes:
      value: |
        実装前に、問題、設計方針、完了条件を整理してください。

  - type: textarea # ユーザーが実際に入力する欄
    id: problem # github側が読み込むid
    attributes:
      label: 解決すべき問題  # 入力欄の見出し
      description: このIssueで何を解決するのか、またなぜ解決しなければならないのかを書く。 # その説明
      placeholder: "例: テクスチャが描画されない" # 例
    validations: # 入力検証
      required: true # 入力が必須か

  - type: textarea
    id: design
    attributes:
      label: 設計方針
      value: |
        #### 【採用方法】

        #### 【この方法を選ぶ理由】

        #### 【メリット】

        #### 【デメリット】
      description: このIssueで問題をどのように解決するのか、またその採用理由を書く。
    validations:
      required: true # 入力必須

  - type: textarea
    id: completion # 完了条件
    attributes:
      label: 完了条件
      value: |
        - [ ] 条件1
        - [ ] 条件2
        - [ ] 条件3
      description: 何が確認できたらこのIssueを閉じられるかを書く。
    validations:
      required: true # 入力必須

  - type: dropdown # ドロップダウンリストを表示する
    id: area # 作業対象を表す
    attributes:
      label: 作業対象領域
      description: このIssueがどこを変更するのかを表す
      multiple: false # 対象領域は巨大Issueを避けるために一つにする(複数を不可)
      options:
        - "area:gameplay" # 移動、戦闘、敵、ゲームルールなど
        - "area:rendering" # Shader,Material,Light,Shadow
        - "area:animation" # アニメーション、遷移
        - "area:world" # 地形、ステージ、背景配置など
        - "area:ui" # HUD、メニュー
        - "area:audio" # BGM,SEなど音関係
        - "area:input" # 入力系(コントローラー、キー、マウス)
        - "area:build" # SDK配布ビルドなど
        - "area:repository" # IssueやGit、テンプレート関連
        - "area:documentation" # README・設定資料・操作説明など
        - "area:other" # どれも該当しないもの
    validations:
      required: true # 入力必須







      
